const posts = [
  {
    _id: 1,
    sender: { id: 1, name: "Dr. Ahmed Hassan", image: null },
    courseId: 1,
    title: "Welcome to Introduction to Computer Science!",
    body: "Welcome everyone to CS101! This semester we will cover programming fundamentals, algorithms, and computational thinking. Please review the syllabus attached.",
    attachmentsId: [],
    type: "announcement",
    deadline: new Date("2024-09-15"),
    createdAt: new Date("2024-09-01"),
  },
  {
    _id: 2,
    sender: { id: 4, name: "Omar Khaled", image: null },
    courseId: 1,
    title: "Question about Assignment 1",
    body: "I'm having trouble understanding the recursion problem in assignment 1. Can someone explain the base case concept?",
    attachmentsId: [],
    type: "question",
    deadline: null,
    createdAt: new Date("2024-09-10"),
  },
  {
    _id: 3,
    sender: { id: 2, name: "Dr. Fatima Ali", image: null },
    courseId: 2,
    title: "Database Project Guidelines",
    body: "The final project requirements have been posted. You will design a complete database system for a real-world application. Teams of 3-4 students are allowed.",
    attachmentsId: [],
    type: "announcement",
    deadline: new Date("2024-12-01"),
    createdAt: new Date("2024-09-05"),
  },
  {
    _id: 4,
    sender: { id: 7, name: "Nour Ahmed", image: null },
    courseId: 2,
    title: "Study Group for Midterm",
    body: "Anyone interested in forming a study group for the upcoming midterm? We can meet at the library or online.",
    attachmentsId: [],
    type: "discussion",
    deadline: null,
    createdAt: new Date("2024-10-01"),
  },
  {
    _id: 5,
    sender: { id: 3, name: "Dr. Karim Nasser", image: null },
    courseId: 3,
    title: "Web Development Workshop",
    body: "Join us for a hands-on workshop on React.js! We'll build a complete web application from scratch.",
    attachmentsId: [],
    type: "discussion",
    deadline: null,
    createdAt: new Date("2024-10-05"),
  },
  {
    _id: 6,
    sender: { id: 5, name: "Layla Mahmoud", image: null },
    courseId: 4,
    title: "Design Patterns Clarification",
    body: "Can someone explain the difference between Factory and Abstract Factory patterns? The textbook explanation is confusing.",
    attachmentsId: [],
    type: "question",
    deadline: null,
    createdAt: new Date("2024-10-08"),
  },
  {
    _id: 7,
    sender: { id: 1, name: "Dr. Ahmed Hassan", image: null },
    courseId: 5,
    title: "Guest Lecture: AI in Healthcare",
    body: "We have a special guest lecture next week from Dr. Smith discussing applications of AI in healthcare.",
    attachmentsId: [],
    type: "announcement",
    deadline: new Date("2024-10-25"),
    createdAt: new Date("2024-10-10"),
  },
  {
    _id: 8,
    sender: { id: 8, name: "Mariam Saeed", image: null },
    title: "Ethical Hacking Resources",
    body: "I found some great resources for practicing ethical hacking. Sharing for anyone interested in cybersecurity!",
    attachmentsId: [],
    type: "discussion",
    deadline: null,
    createdAt: new Date("2024-10-12"),
  },
  {
    _id: 9,
    sender: { id: 6, name: "Youssef Ibrahim", image: null },
    title: "React Native vs Flutter?",
    body: "For our final project, should we use React Native or Flutter? What are the pros and cons of each?",
    attachmentsId: [],
    type: "question",
    deadline: null,
    createdAt: new Date("2024-10-15"),
  },
  {
    _id: 10,
    sender: { id: 2, name: "Dr. Fatima Ali", image: null },
    title: "MongoDB Workshop Announcement",
    body: "Important: We will have a hands-on MongoDB workshop. Please install MongoDB locally before attending.",
    attachmentsId: [],
    type: "announcement",
    deadline: new Date("2024-11-01"),
    createdAt: new Date("2024-10-18"),
  },
];

module.exports = posts;