const users2 = [
  {
    _id: "1",
    name: "Dr. Ahmed Hassan",
    email: "ahmed.hassan@gmail.com",
    password: "$2b$10$hashedpassword1",
    role: "instructor",
    level: "Professor",
    image: {},
    createdAt: new Date("2024-01-15"),
  },
  {
    _id: "2",
    name: "Dr. Sarah Mohamed",
    email: "sarah.mohamed@gmail.com",
    password: "$2b$10$hashedpassword2",
    role: "instructor",
    level: "Associate Professor",
    image: {},
    createdAt: new Date("2024-01-20"),
  },
  {
    _id: "3",
    name: "Dr. Ahmed Fahmy",
    email: "ahmed.fahmy@gmail.com",
    password: "$2b$10$hashedpassword3",
    role: "instructor",
    level: "Professor",
    image: {},
    createdAt: new Date("2024-01-01"),
  },
  {
    _id: "4",
    name: "Omar Khaled",
    email: "omar.khaled@gmail.com",
    password: "$2b$10$hashedpassword4",
    role: "student",
    level: "Junior",
    image: {},
    createdAt: new Date("2024-02-01"),
  },
  {
    _id: "5",
    name: "Fatima Ali",
    email: "fatima.ali@gmail.com",
    password: "$2b$10$hashedpassword5",
    role: "student",
    level: "Senior",
    image: {},
    createdAt: new Date("2024-02-05"),
  },
  {
    _id: "6",
    name: "Youssef Ibrahim",
    email: "youssef.ibrahim@gmail.com",
    password: "$2b$10$hashedpassword6",
    role: "student",
    level: "Sophomore",
    image: {},
    createdAt: new Date("2024-02-10"),
  },
  {
    _id: "7",
    name: "Nour Ahmed",
    email: "nour.ahmed@gmail.com",
    password: "$2b$10$hashedpassword7",
    role: "student",
    level: "Junior",
    image: {},
    createdAt: new Date("2024-02-15"),
  },
  {
    _id: "8",
    name: "Mohamed Samir",
    email: "mohamed.samir@gmail.com",
    password: "$2b$10$hashedpassword8",
    role: "student",
    level: "Freshman",
    image: {},
    createdAt: new Date("2024-03-01"),
  },
  {
    _id: "9",
    name: "Layla Mahmoud",
    email: "layla.mahmoud@gmail.com",
    password: "$2b$10$hashedpassword9",
    role: "student",
    level: "Senior",
    image: {},
    createdAt: new Date("2024-03-05"),
  },
  {
    _id: "10",
    name: "Dr. Karim Nasser",
    email: "karim.nasser@gmail.com",
    password: "$2b$10$hashedpassword10",
    role: "instructor",
    level: "Assistant Professor",
    image: {},
    createdAt: new Date("2024-01-25"),
  },
];

module.exports = users2;
